konflux-ci/quality-dashboard

.github/workflows/container-build.yaml

Create a simple CI jobs to push to quay both quality dashboard images.
Signed-off-by: Flavius <flacatus@redhat.com>

Build containers in CI

---

.gitignore
backend/cmd/qe-dashboard-backend/main.go
backend/deploy/openshift/deployment.yaml
backend/deploy/openshift/pgweb.yaml
backend/deploy/openshift/route.yaml
backend/deploy/openshift/secret.yaml
backend/deploy/openshift/service.yaml
backend/pkg/utils/utils.go

- Added Pg web for better view inside the RDS db
- Added configuration that is Required inorder to move to RDS 
- JIRA:  https://issues.redhat.com/browse/RHDP-441

chore: Connect to RDS and pg web

---

backend/Dockerfile

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

RHDP-514 Update ubi image for backend

---

backend/api/server/rotate.go
backend/deploy/openshift/deployment.yaml
backend/deploy/openshift/postgres.yaml
backend/deploy/openshift/route.yaml
backend/deploy/openshift/service.yaml
hack/install.sh

This Pull request change the postgres image for local testing

Fix postgress images pointing to redhat-appstudio-qe

---

backend/api/server/router/repositories/repositories.go
frontend/src/app/Jobs/Jobs.tsx
frontend/src/app/utils/APIService.ts

- Unfortunately, the changes in PR #31 introduced a panic (that I did not catch before committing). The current PR will fix it.
- Also improved `ContextSelectorItem` of Jobs component

fix: panic in function 'getAllRepositoriesWithOrgs'

---

frontend/deploy/base/deployment.yaml
frontend/deploy/base/route.yaml
frontend/deploy/base/secret.yaml
frontend/deploy/base/service-account.yaml
frontend/deploy/base/service.yaml
frontend/deploy/overlays/local/kustomization.yaml
frontend/users.htpasswd

Changes 
- _(Temp)_ remove secret from secret generator (**Will be Rolled back with a better fix**)
- Add a new secret which will work until secret generation is possible with sync waves 
- Use ArgoCD sync waves set -1 for secret and 0 for deployment

fix: Secret Creation sync error

---

backend/pkg/storage/ent/client/prow_metrics.go

- Fix Total CI Jobs to only consider finished jobs (jobs with SuccessState, FailureState, or ErrorState)
[AD-56](https://issues.redhat.com/browse/AD-56)

AD-56: fix Total CI Jobs to only consider finished jobs

---

.tekton/pull-request-backend.yaml
.tekton/pull-request-frontend.yaml
.tekton/push-backend.yaml
.tekton/push-frontend.yaml

Switching to new bundle since development of old one was stopped before attempt to migrate to kcp. New bundle is removing dependency on shared secret.

STONEBLD-777 - tekton-ci: update bundle

---

frontend/deploy/base/kustomization.yaml

Solution 1 on fixing dashboard auth secret
signed off by msawood@redhat.com

fix: Secret dashboard auth secret 

---

frontend/src/app/Jira/Jira.tsx

- fix undefined cases in sortRows

[Jira page] fix undefined cases in sortRows

---

frontend/src/app/utils/APIService.ts

- update axios timeout in `updateTeam` in order to avoid timeout errors when editing jira projects in the team page

update axios timeout in updateTeam

---

frontend/src/app/Github/Github.tsx
frontend/src/app/Reports/Reports.tsx
frontend/src/app/utils/utils.ts

- Some pages take some time to load data from the backend like GitHub and OpenShift CI pages. In other to make the loading more subtle, this PR adds a spinner
[AD-75](https://issues.redhat.com/browse/AD-75)

[AD-75] add loading to GitHub and OpenShift CI pages

---

frontend/Dockerfile

https://issues.redhat.com/browse/RHTAPBUGS-120

RHTAPBUGS-120: Add a timeout to yarn install dependencies

---

backend/api/server/middleware/auth.go
backend/cmd/server/main.go
backend/go.mod
backend/go.sum

This PR consist on adding a new dex middleware to verify backend routes.

Add authenticated routes

---

frontend/src/app/Github/PullRequests.tsx
frontend/src/app/Jira/Jira.tsx
frontend/src/app/utils/APIService.ts

- [AD-67] add Bugs affecting CI to Jira plugin
- [AD-91] remove `Resolved at` and `Resolution time` in open bugs in Jira plugin
- format `Create at`, `Update at`, and `Resolved at` from `2023-05-04T19:44:21Z` to `2023-05-04 19:44:21` in Jira plugin
[AD-67](https://issues.redhat.com/browse/AD-67)
[AD-91](https://issues.redhat.com/browse/AD-91)

[AD-67] add Bugs affecting CI to Jira plugin and [AD-91] remove resolved at and resolution time in open bugs

---

frontend/package.json
frontend/src/app/Reports/utils.tsx
frontend/src/app/utils/DateTimeRangePicker.tsx
frontend/yarn.lock

- fix the time selector in the date range selector
- bump `@patternfly/react-core` from `4.162.3` to `4.276.8`

[AD-99] Time selector does not work in date range selector

---

frontend/src/app/Github/CodeCov.tsx
frontend/src/app/Github/CreateRepository.tsx
frontend/src/app/Github/Github.tsx
frontend/src/app/Github/GithubActions.tsx
frontend/src/app/Github/Metrics.tsx
frontend/src/app/Github/PullRequests.tsx
frontend/src/app/Github/Table.tsx
frontend/src/app/Jira/Jira.tsx
frontend/src/app/Reports/Reports.tsx
frontend/src/app/utils/APIService.ts
frontend/src/app/utils/DateTimeRangePicker.tsx
frontend/src/app/utils/sharedComponents.tsx

- Added Global GitHub view with improvements:
- coverage trend
- retest before merge count per range date time
- link to the GitHub repository
[AD-84](https://issues.redhat.com/browse/AD-84)

AD-84 frontend: global GitHub view

---

backend/api/server/router/prow/prow_metrics.go
backend/pkg/storage/ent/client/prow_metrics.go
backend/pkg/storage/storage.go
frontend/src/app/Reports/Reports.tsx

https://issues.redhat.com/browse/AD-106

temporary log error to dig AD-106

---

frontend/src/app/routes.tsx

Add protected route option to new plugin

Update routes.tsx to protected route

---

frontend/src/app/utils/APIService.ts

Replace fetch call with axios call so the auth token get sent automatically to backend endpoints

Replace fetch call with axios call 

---

.github/workflows/validate-pr.yaml
README.md

This PR specifies the Postgres version as the latest version is not compatible.

fix: Postgres version

---

backend/api/server/rhtap_bug_slis_alert.go
backend/api/server/router/jira/bug_slos.go
frontend/src/app/BugSLIs/MainPage.tsx

- improve Bug SLI page description + change rhtap bug slis alerts slack channel

improve Bug SLI page description + change rhtap bug slis alerts slack channel

---

backend/api/server/rhtap_bug_slis_alert.go
backend/go.mod
backend/go.sum

fix hour to send slis alerts every day at 9am

fix hour to send slis alerts

---

backend/api/server/rhtap_bug_slis_alert.go

Slack thread: https://redhat-internal.slack.com/archives/C062AF1RFK8/p1698766139674879

disable teams mention

---

README.md
backend/api/apis/failure/v1alpha1/failure.go
backend/api/server/failure_rotate.go
backend/api/server/router/failure/failure.go
backend/api/server/router/failure/types.go
backend/pkg/storage/ent/client/failure.go
backend/pkg/storage/ent/client/jira_bugs.go
backend/pkg/storage/storage.go
frontend/src/app/CiFailures/CiFailures.tsx
frontend/src/app/CiFailures/CreateFailure.tsx
frontend/src/app/utils/APIService.ts

'RHTAPBUGS Impact on CI' plugin is not working when adding a new entry. That happens during the insert of the Jira Key. Since we are validating the Jira Key while the user is writing, the backend returns an error, and the auth session fails/expires, which makes "impossible" to add a new entry.
- Removed Jira Key validation for now
- Improvements on 'RHTAPBUGS Impact on CI' plugin
[AD-128](https://issues.redhat.com/browse/AD-128)

AD-128: RHTAPBUGS Impact on CI not working when adding a new entry

---

backend/api/server/rhtap_bug_slis_alert.go

- Bug SLIs alerts were reporting closed issues because the function that gets the Open RHTAPBUGS was only called once. This function should be called every time the alerts should be sent.
[AD-135](https://issues.redhat.com/browse/AD-135)

AD-135 - fix 'Bug SLIs alerts are reporting closed issues'

---

backend/api/server/rotate.go

Fetch data for analysis every 40 minutes instead of every 10 seconds to avoid rate limits

---

backend/pkg/storage/ent/client/failure.go
frontend/src/app/FlakeyTests/FlakeyTests.tsx
frontend/src/app/FlakyTests/FlakyTests.tsx
frontend/src/app/utils/APIService.ts

The frequency of each bug in the RHTAPBUGS Impact on CI list is 0%. Since I was not able to reproduce it locally, this PR adds some temporary logs
[AD-138](https://issues.redhat.com/browse/AD-138)

adding logs to dig AD-138

---

README.md

- We do not have any documentation regarding RHTAPBUGS IMPACT on CI and we have a few documentation regarding Bug SLIs. So, this PR addresses these gaps.
[AD-136](https://issues.redhat.com/browse/AD-136)

AD-136 - add RHTAPBUGS IMPACT on CI doc and improve Bug SLIs doc

---

frontend/src/app/Teams/User.tsx

Fix undefined edge case in User.tsx

---

frontend/src/app/store/store.tsx

Seems like UserStore can return undefined

Fix quality dashboard store

---

frontend/src/app/Reports/Reports.tsx

fix time range auto apply

---

backend/api/server/router/repositories/repositories.go

change error code to bad request

---

frontend/src/app/Reports/Reports.tsx
frontend/src/app/utils/APIService.ts

Fix no-jobs case in Test Report page and avoid the infinite loading icon

Fix no-jobs case in Test Report page

---

frontend/src/app/Jira/Jira.tsx

- We need to clean the Jira issues table every time 'Bugs affecting CI' is selected
[AD-165](https://issues.redhat.com/browse/AD-165)

AD-165 - clean Jira issues table every time 'Bugs affecting CI' is selected

---

backend/deploy/base/deployment.yaml
frontend/.env

backend in prod is consistently restarting because it reaches the memory limit (OOMKilled)

increase backend memory

---

backend/api/server/router/repositories/repositories.go
backend/api/server/router/repositories/repositories_route.go
frontend/src/app/Github/CreateRepository.tsx
frontend/src/app/Teams/TeamsOnboarding.tsx
frontend/src/app/utils/APIService.ts

-  Improve "Add a repository" page when creating new team or adding a new repo in GitHub plugin
[AD-166](https://issues.redhat.com/browse/AD-166)

AD-166 - improve "Add a repository" page when creating new team or adding a new repo in GitHub plugin

---

frontend/src/app/Teams/TeamsOnboarding.tsx

improve gh regex

---

backend/pkg/storage/ent/client/suites_ocurrencies.go
frontend/src/app/FlakyTests/FlakyTests.tsx
frontend/src/app/FlakyTests/Types.tsx

When getting the frequency of the suite failure, we need to filter them by job name.
[AD-161](https://issues.redhat.com/browse/AD-161)

AD-161: Add missing job name filter when getting the frequency of the suite failure

---

.tekton/pull-request-backend.yaml
.tekton/pull-request-frontend.yaml
.tekton/push-backend.yaml
.tekton/push-frontend.yaml
backend/deploy/base/deployment.yaml
backend/deploy/base/route.yaml
backend/deploy/base/service.yaml
backend/deploy/overlays/local/postgres.yaml
dex/deploy/base/deployment.yaml
dex/deploy/base/kustomization.yaml
dex/deploy/base/route.yaml
dex/deploy/base/service.yaml
dex/devfile.yaml
frontend/.dockerignore
frontend/Dockerfile
frontend/deploy/base/deployment.yaml
frontend/deploy/base/service-account.yaml
frontend/deploy/base/service.yaml
frontend/entrypoint.sh
hack/install.sh

[KONFLUX-2244](https://issues.redhat.com/browse/KONFLUX-2244)
Tested together with changes in https://github.com/redhat-appstudio/infra-deployments/pull/3370

feat: re-add QD to tekton-ci

---

backend/deploy/base/deployment.yaml

fix: backend: sync issue

---

backend/api/server/router/prow/job.go
backend/api/server/router/repositories/repositories.go
frontend/src/app/Reports/Reports.tsx

Until now only Openshift CI were added to the metrics. Since Konflux team migrated from Opensfhit ci to Konflux CI now we need to show all metrics in the dasshboard

get all repositories for metrics instead of only the openshift ci ones
