konflux-ci/quality-dashboard

- .tekton/pull-request-backend.yaml
- .tekton/pull-request-frontend.yaml
- .tekton/push-backend.yaml
- .tekton/push-frontend.yaml
This PR creates 4 PaC Pipelines
- dashboard-backend-on-pull-request
- Builds backend image and pushes it to `quay.io/redhat-appstudio/pull-request-builds` as it's usual with other services
- dashboard-backend-on-pull-request
- Builds frontend image and pushes it to `quay.io/redhat-appstudio/pull-request-builds`
- dashboard-backend-on-push
- Runs on merge to `main` branch
- Builds the image
- Publishes it in quay.io/redhat-appstudio/quality-dashboard-backend
- Creates PR in `infra-deployments` repo with latest changes
- dashboard-frontend-on-push
- Runs on merge to `main` branch
- Builds the image
- Publishes it in quay.io/redhat-appstudio/quality-dashboard-frontend
- Creates PR in `infra-deployments` repo with latest changes
I've tested this PR just partially as it is really hard to setup …
> feature: AD-36 - setup PaC for quality dashboard

- .tekton/push-backend.yaml
- .tekton/push-frontend.yaml
We have to have target branch configured to `refs/heads/main` in order for the push PipelineRun to be started, but then it doesn't work with Re-Run button for rerunning the pipeline. 
I've registered https://issues.redhat.com/browse/SRVKP-2692 bug with PaC, but in the meantime I was suggested to use `*main` instead (https://coreos.slack.com/archives/C0382KN768J/p1671027909826279?thread_ts=1671027265.427709&cid=C0382KN768J)
Signed-off-by: Radim Hopp <rhopp@redhat.com>
> 🐛 fix target_branch in PaC

- .tekton/pull-request-frontend.yaml
- .tekton/push-frontend.yaml
- frontend/deploy/overlays/local/kustomization.yaml
Before this change, local deployment (using kustomize directly, or by running `./hack/install.sh`) failed with
```
Error: merging from generator &{0xc001a84000 {  map[] map[]} {{ quality-dashboard-configmap replace {[] [] [configmap.txt] } <nil>}}}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"ConfigMap", isClusterScoped:false}, Name:"quality-dashboard-configmap", Namespace:""} does not exist; cannot merge or replace
```
This is probably overlook of when I had also configmap in base layer in this repo... but that configmap was finally moved to infra-deployments.
Signed-off-by: Radim Hopp <rhopp@redhat.com>
> 🐛 Fix local frontend deployment

- .tekton/push-backend.yaml
- .tekton/push-frontend.yaml
Since PaC 1.5.0 is already installed on staged cluster  and [PaC 1.5.0](https://github.com/openshift-pipelines/pipelines-as-code/releases/tag/v0.15.0) contains fix for [SRVKP-2692](https://issues.redhat.com/browse/SRVKP-2692), this change should solve our "problems" ;-)
Signed-off-by: Radim Hopp <rhopp@redhat.com>
> 🐛 AD-36 fix of push pipelines after SRVKP-2692 fix

- frontend/src/app/Reports/Reports.tsx
- frontend/src/app/utils/sharedComponents.tsx
- Add link to the job history
There is a limitation of 12h for the links. Both global link (https://prow.ci.openshift.org/?repo=redhat-appstudio%2Finfra-deployments&type=periodic) and specific job link (https://prow.ci.openshift.org/?repo=redhat-appstudio%2Finfra-deployments&type=periodic&job=periodic-ci-redhat-appstudio-infra-deployments-main-hacbs-e2e-periodic) will present job history regarding the last 12h. So, the number of total jobs will be different for the jobs that appear in the link. 
[AD-59](https://issues.redhat.com/browse/AD-59)
> AD-59: Add link to the job history

- backend/api/server/router/teams/teams.go
- backend/pkg/storage/ent/client/jira_bugs.go
- backend/pkg/storage/ent/client/types.go
- backend/pkg/storage/ent/db/bugs.go
- backend/pkg/storage/ent/db/bugs/bugs.go
- backend/pkg/storage/ent/db/bugs/where.go
- backend/pkg/storage/ent/db/bugs_create.go
- backend/pkg/storage/ent/db/bugs_update.go
- backend/pkg/storage/ent/db/migrate/schema.go
- backend/pkg/storage/ent/db/mutation.go
- backend/pkg/storage/ent/schema/jira_bugs.go
- backend/pkg/storage/storage.go
- frontend/src/app/Teams/TeamsOnboarding.tsx
- frontend/src/app/Teams/TeamsTable.tsx
- When editing a team, list the Jira projects associated with the target team on "Chosen options"
- Include the Jira project key in the list of projects
- Update jira page when editing jira keys
[AD-77](https://issues.redhat.com/browse/AD-77)
[AD-78](https://issues.redhat.com/browse/AD-78)
> AD-77 and AD-78: populate "Chosen options" + include the Jira project key in the list of projects

- backend/api/apis/jira/v1alpha1/bugs_types.go
- backend/api/server/router/jira/jira.go
- backend/api/server/router/jira/jira_route.go
- backend/pkg/storage/ent/client/jira_bugs.go
- backend/pkg/storage/ent/client/utils.go
- backend/pkg/storage/storage.go
- frontend/src/app/Github/PullRequests.tsx
- frontend/src/app/Jira/Jira.tsx
- frontend/src/app/Reports/Reports.tsx
- frontend/src/app/Teams/TeamsSelect.tsx
- frontend/src/app/utils/APIService.ts
- frontend/src/app/utils/sharedComponents.tsx
- frontend/src/app/utils/utils.ts
- [AD-95] enable to zoom in into time period in Jira, Github, and OpenShift CI charts
- added improvements on Jira:
-  changed resolution time from hours to days (backend) 
-  changed jira bugs data from months to days (backend)
-  changed default time range to 30 days instead of 12 months
-  added time range support
-  added custom routes support 
-  added loading page
[AD-95](https://issues.redhat.com/browse/AD-95)
> [AD-95] - enable to zoom in into time period

- backend/deploy/base/deployment.yaml
- frontend/deploy/base/deployment.yaml
Set runAsNonRoot and  readOnlyRootFilesystem to true for pods/containers.
> Fix kube-linter issues

- frontend/deploy/base/deployment.yaml
The entrypoint is changing files using sed so the container fails to start since readOnlyRootFilesystem was introduced in bb70cddf67540b46a218024ac29f520f7a63dd2e
> Revert readOnlyRootFilesystem for quality-frontend-dashboard container

- backend/api/server/router/jira/bug_slos.go
- backend/pkg/connectors/github/repositories.go
The present PR fixes the following panic:
```
2023-10-20T16:48:08.553Z	info	server/server.go:215	Registering route	{"Path": "/api/quality/failures/delete", "Method": "DELETE"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe289d6]
goroutine 31 [running]:
github.com/redhat-appstudio/quality-studio/api/server/router/jira.measureBugResolutionSLI(0x4044000000000000, 0x4034000000000000, 0xc000002780)
/github.com/redhat-appstudio-qe/qe-dashboard-backend/api/server/router/jira/bug_slos.go:55 +0x96
github.com/redhat-appstudio/quality-studio/api/server/router/jira.GetResolutionSLI(0xc000002780)
/github.com/redhat-appstudio-qe/qe-dashboard-backend/api/server/router/jira/bug_slos.go:85 +0x9e …
```
> fix nil pointer

- frontend/src/app/utils/APIService.ts
- OpenShift CI page is empty due to usage of fetch on function `getProwJobStatistics`. Somehow, the `Authorization` header is invalid.  The present PR changes fetch usage to axios.
[AD-106](https://issues.redhat.com/browse/AD-124)
> AD-124: fix OpenShift CI page is empty

- backend/api/apis/github/v1alpha1/prs.go
- backend/pkg/connectors/github/pull_requests_query.go
This PR adds PULL_REQUEST_COMMIT to graphql query for getting TimelineItems. This change makes it possible to determine time of the last commit before merging a PR. It also changes the number of PRs returned per query to avoid timeout.
Issue:
[AD-120](https://issues.redhat.com/browse/AD-120)
> fix: [AD-120] Correcting Retest Before Merge Avg metric

- backend/api/server/server.go
- backend/pkg/connectors/github/content.go
Backend logs have a lot of logs regarding not finding a repository in Openshift CI. This is normal since some repos like dora-metrics do not have jobs running. To clean them, this PR replaces error log with warn log.
> replace error log with warn log when resp status is 404 in CheckIfRepoExistsInOpenshiftCI

- backend/api/apis/prow/v1alpha1/metrics.go
- backend/pkg/storage/ent/client/prow_metrics.go
- frontend/src/app/Reports/Reports.tsx
- frontend/src/app/utils/sharedComponents.tsx
This PR adds whole numbers under percentages to cards in OpenShift CI Test Report Page.
Issue:
[AD-108](https://issues.redhat.com/browse/AD-108)
New OpenShift CI Test Report Page look:
> feat: [AD-108] Display whole numbers within the OpenShift CI Test Report Page

- backend/pkg/storage/ent/client/utils.go
backend-linter is failing with ```func `handleNaN` is unused (unused)```
> delete handleNaN func

- backend/api/apis/github/v1alpha1/prs.go
- backend/pkg/storage/ent/client/pullrequests.go
- frontend/src/app/Github/Github.tsx
- frontend/src/app/Github/Metrics.tsx
- frontend/src/app/Github/PullRequests.tsx
This PR adds tiles with counts of created and merged PRs in selected time range to the Github page.
Issue:
[AD-102](https://issues.redhat.com/browse/AD-102)
New Github Metrics page look:
> [AD-102] Add count of Merged/Created PRs on GitHub Page

- backend/pkg/storage/ent/client/jira_bugs.go
- backend/pkg/storage/ent/client/utils.go
- Exclude weekend days in SLIs for Triage and Response Time
**Triage Time Bug SLI**: Priority should not be undefined for more than 2 days on untriaged bugs
**Response Time Bug SLI**: Assignee should not be undefined for more than 2 days on Blocker and Critical bugs
Currently, SLIs for Triage and Response Time are considered the weekend days.
If an issue is opened on Friday and does not meet the defined Bug SLOs on that day, the teams will see the alert on Monday reporting that they do not meet the Bug SLOs (because the SLIs are short. In these cases, 2 days). However, they should not been alert since they did not have 2 working days to address the SLOs.
To avoid it, we should skip weekends in SLIs for Triage and Response Time metrics.
[AD-134](https://issues.redhat.com/browse/AD-134)
> AD-134 - Exclude weekend days in SLIs for Triage and Response Time

- backend/pkg/storage/ent/client/jira_bugs.go
- backend/pkg/storage/ent/client/utils.go
- frontend/src/app/BugSLIs/Table.tsx
- Currently, the Resolution Time Bug SLO metric is not considering only working days. We should change it in order to align with Response Time Bug SLO and Triage Time Bug SLO metrics that already consider only working days.
[AD-137](https://issues.redhat.com/browse/AD-137)
> AD-137 - Use only working days in all metrics in the Bug SLOs

- backend/pkg/storage/ent/client/failure.go
The frequency of each bug in the RHTAPBUGS Impact on CI list is 0%. Since I was not able to reproduce it locally, this PR adds some temporary logs
[AD-138](https://issues.redhat.com/browse/AD-138)
> adding logs to dig AD-138

- backend/pkg/connectors/gcs/gcs_authentication.go
GCS bucket name for ci jobs has changed. This PR should update it to the new correct one. ([thread](https://redhat-internal.slack.com/archives/CFUGK0K9R/p1702999988408109))
> Update gcs bucket name

- backend/api/server/rhtap_bug_slis_alert.go
The current code is pointing to `build-api-team` but it should be `konfluxbld-green`
> bug slis alert: fix build-api-team to konfluxbld-green

- backend/api/server/rhtap_bug_slis_alert.go
- backend/api/server/router/jira/jira.go
- backend/pkg/storage/ent/client/jira_bugs.go
- backend/pkg/storage/storage.go
- frontend/src/app/BugSLIs/MainPage.tsx
- frontend/src/app/utils/APIService.ts
At the moment, bug slis alerts are only available for RHTAPBUGS. Since we will need also KFLUXBUGS, we will need to address it. So, in the short term, we will need to:
- rename the channel [#rhtap-bug-slis-alerts](https://redhat-internal.slack.com/archives/C062AF1RFK8) to konflux-bug-slis-alerts
- update the plugin to look only at the KFLUXBUGS project
[AD-167](https://issues.redhat.com/browse/AD-167)
> AD-167 -  konflux bug slis

- backend/api/server/rotate.go
- backend/pkg/storage/ent/client/jira_bugs.go
- frontend/src/app/Jira/utils.tsx
The Jira page is empty for DevConsole team with OCPBUGS as project because this project has a lot of issues. 
GetBugsByJQLQuery function is failing with:
`2024-02-12T09:05:05.726Z        info    server/rotate.go:31      Update failed: insert nodes to table "bugs": pq: got 646231 parameters but PostgreSQL only supports 65535 parameters`
So, we need to split the bulks when creating issues.
[AD-171](https://issues.redhat.com/browse/AD-171)
> AD-171: split bulk when creating a large number of jira bugs

- frontend/src/app/Reports/Reports.tsx
- frontend/src/app/Teams/TeamsTable.tsx
If there is an edge case, where the default team is deleted, we need to update the default team in user settings to be "n/a", until the user configures it again.
[AD-182](https://issues.redhat.com/browse/AD-182)
> AD-182: Update default team in user settings when deleting the default team

- README.md
The current link in README https://www.patternfly.org/v4/get-started/develop/ leads to a 404 error page. 
Change the link to a working one: https://www.patternfly.org/get-started/develop/
> docs: update link to the patternfly project

- README.md
- backend/api/server/router/jira/jira.go
- backend/pkg/storage/ent/client/jira_bugs.go
- frontend/src/app/AppLayout/AppLayout.tsx
- frontend/src/app/CiFailures/CiFailures.tsx
- frontend/src/app/CiFailures/CreateFailure.tsx
- frontend/src/app/routes.tsx
- frontend/src/app/utils/Header.tsx
- frontend/src/app/utils/utils.ts
Currently, the RHTAPBUGS Impact on CI page is "designed" only for the RHTAPBUGS project (of the KONFLUX team). This page should be designed for any team.
- Changed `Plugins` to `Metrics`
- Changed the `RHTAPBUGS Impact on CI` page to `Bug CI Impact`
- Added some tips and explanations regarding what the page does and what means ('Learn more' button).
- Added validation of the Jira Key when the user adds a new entry.
[AD-175](https://issues.redhat.com/browse/AD-175)
> AD-175: CI Impact of a bug should be available for any team’s project

- backend/pkg/utils/utils.go
Backend linter fails with:
```
pkg/utils/utils.go:99:11: Error return value of `rand.Read` is not checked (errcheck)
rand.Read(bytes)
```
> fix lint error

- backend/devfile.yaml
backend in prod is consistently restarting because it reaches the memory limit (OOMKilled)
> increase backend memory

- backend/api/server/prow_rotate.go
change "Failed to get pr number from" log from Warn to Debug to avoid a lot of warnings in the logs
> change "Failed to get pr number from" log from Warn to Debug

- .tekton/push-backend.yaml
- .tekton/push-frontend.yaml
The old version of the script was replacing the frontend/backend manifests (depending on which component made if first to infra-deployments PR) and the resulted PR contained only the change to a **single component** (backend or frontend)
This PR fixes it by keeping the `infra-deployment-update-script` only in a single component (frontend) and the script updates git revision (git ref and image tag) for all 3 components (backend, dex, frontend) at once
> fix: infra-deployments update script

- backend/api/server/prow_rotate.go
- backend/pkg/connectors/codecov/codecov_test.go
- backend/pkg/storage/ent/client/repository_test.go
- frontend/src/app/FlakyTests/FlakyTests.tsx
There are some function calls where the github organization is hardcoded. After migration to `konflux-ci`, these wouldn't work for example for infra-deployments repo, that stays in `redhat-appstudio` github org.
Keeping "redhat-appstudio" github org even for migrated repositories should be fine, because github automatically redirects API calls to the new organization ("konflux-ci")
I filed a jira for fixing this: https://issues.redhat.com/browse/AD-193
> fix: github org in function calls

- README.md
Parentheses and brackets in the link are accidentally switched in the README. 
This PR fixes that resulting in a properly formatted Markdown link to the failure code.
> docs: fix link to failure code

- .tekton/pull-request-backend.yaml
- .tekton/pull-request-frontend.yaml
- .tekton/push-backend.yaml
- .tekton/push-frontend.yaml
* fixed the syntax for referencing pipeline bundles
* replaced the bundle ref with the one that was migrated to konflux-ci quay org: `quay.io/konflux-ci/tekton-catalog/pipeline-core-services-docker-build:latest`
> fix: pipeline references
